# Use root/example as user/password credentials
version: '3'

services:
  mongo:
    container_name: reddit_mongo_db
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - ./dataDb:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
